# Site Settings
title: "Adithya Giridharan"
description: "Aspiring PhD candidate in Machine Learning & Sports Analytics"
author: "Adithya Giridharan"
email: "giridharanadithya@gmail.com"  # Use your real email
location: "Pune, India"
github_username: ADITHYAG73
bio: "ML Engineer transitioning to research in RL for sports analytics, LLMs, and graph machine learning"

# Site configuration
url: "https://adithyag73.github.io"
baseurl: ""
repository: "ADITHYAG73/ADITHYAG73.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Asia/Kolkata

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:name/
  publications:
    output: true
    permalink: /:collection/:name/
  portfolio:
    output: true
    permalink: /:collection/:name/
  talks:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Social media
social:
  type: Person
  name: Adithya Giridharan
  links:
    - "https://github.com/ADITHYAG73"
    - "https://medium.com/@AdithyaGiridharan"
    - "https://www.kaggle.com/adithyagiri"

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name: "Adithya Giridharan"
  avatar: "/images/profile.png"  # Add your photo later
  bio: "ML Engineer transitioning to research in RL for sports analytics, LLMs, and graph machine learning"
  location: "Pune, India"
  employer:
  pubmed:
  googlescholar:
  email: "giridharanadithya@gmail.com"
  researchgate:
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "ADITHYAG73"
  google_plus:
  keybase:
  instagram:
  impactstory:
  lastfm:
  linkedin:
  orcid:
  pinterest:
  soundcloud:
  stackoverflow:
  steam:
  tumblr:
  twitter:
  vine:
  weibo:
  xing:
  youtube:

# Reading Files
include:
  - .htaccess
  - _pages

# Exclude these files from production site
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
