title: "Adithya Giridharan"
description: "Aspiring PhD candidate in Machine Learning & Sports Analytics"
author: "Adithya Giridharan"
email: "your-email@domain.com"
location: "Pune, India"
github_username: ADITHYAG73
# Add research interests
bio: "ML Engineer transitioning to research in RL for sports analytics, LLMs, and graph machine learning"
